# Generated by Django 4.0 on 2023-11-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_inventario_inventario_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='inventario_item',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='inventario_medicamento',
        ),
    ]
